export const tagTypes: Record<string, string> = {
  auth: "auth",
  user: "users",
  divisions: "divisions",
  districts: "districts",
  upzelas: "upzelas",
  orders: "orders",
  addresses: "addresses",
  wishlists: "wishlists",
  products: "products",
  carts: "carts",
  product_categories: "product-categories",
  video_gallery_categories: "video_gallery_categories",
  video_gallaries: "video-gallaries",
  blog_category: "blog-category",
  blog: "blog",
  blog_details: "blog-details",
  testimonials: "testimonials",
  question_answers: "question-answers",
};

export const tagTypesList: string[] = [
  tagTypes.auth,
  tagTypes.user,
  tagTypes.divisions,
  tagTypes.districts,
  tagTypes.upzelas,
  tagTypes.orders,
  tagTypes.addresses,
  tagTypes.wishlists,
  tagTypes.products,
  tagTypes.carts,
  tagTypes.product_categories,
  tagTypes.video_gallery_categories,
  tagTypes.video_gallaries,
  tagTypes.blog_category,
  tagTypes.blog,
  tagTypes.blog_details,
  tagTypes.testimonials,
  tagTypes.question_answers,
];
